repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
    - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-tidy-imports
    - flake8-typing-imports
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.254'
    hooks:
    - id: ruff
